### ISSUE TITLE
Variabele?

### ISSUE THREAD

**Issue by vasilisvg** [jelleoverbeek/cssttr#6]
https://github.com/jelleoverbeek/cssttr/blob/7a31a89f77c699eaf37b89eb5c6e9f6807233d5a/assets/css/styles.css#L758
Had dit getal niet beter in een custom property gekund? Als je hem nu wil aanpassen moet dat op een paar plekken

**Comment by jelleoverbeek** [comment]
custom properties werken helaas niet met media queries 👎 
https://stackoverflow.com/questions/40722882/css-native-variables-not-working-in-media-queries

**Comment by vasilisvg** [comment]
Nu ik dat zo lees is het logisch! Dank je wel voor de link, weer wat geleerd!
